### ISSUE TITLE
HttpException: Headers size exceeded the of '8192' bytes

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#156]
@jayudey-wf reported that when trying to do a large file transfer, this error may be encountered:

```
Unhandled exception:
HttpException: Headers size exceeded the of '8192' bytes
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Need to do some research on maximum header & body sizes. I believe all that will be necessary in this case is to catch the `HttpException` and wrap it in a `RequestException` and then add some documentation around this issue.

**Comment by thosakwe** [comment]
Were you ever able to fix this issue on your end? I'm encountering the same in [Angel](https://github.com/angel-dart/angel)
when proxying `pub serve`. I feel like it has to do with this issue:

https://github.com/dart-lang/sdk/issues/28251

I don't think using a reusable buffer is the solution - that's what Angel already does, and still encounters this error.

Cheers!

**Comment by evanweible-wf** [comment]
@thosakwe unfortunately I haven't looked into it any further - it is only an issue with our example server and not with this package so it hasn't been a high priority.
